
data = [
        {
            avatar: "nullavatar--1651724493234.jpg,https://api.philiamatch.com/storage/public/avatars/avatar--1653130712850.jpg,",
            catchyPhrase: "Google",
            createdAt: "2022-05-04T19:09:29.000Z",
            dateOfBirth: "22/12/2400",
            email: "cokeradamms@gmail.com",
            firstName: "Coker Adams",
            gender: "Male",
            genoType: "AA",
            hobby: "Coding",
            id: 1,
            inSearch: "Search",
            interest: "Interest",
            isMatched: true,
            latitude: "3456789",
            longitude: "3456789",
            loveLang: "Love",
            nationality: "Nigerian",
            religion: "Islam",
            tribe: "Yoruba",
            updatedAt: "2022-05-21T10:58:33.000Z",
            user_id: 1,
        },
        {
            avatar: "nullhttps://api.philiamatch.com/storage/public/avatars/avatar--1653131490579.jpg,",
            catchyPhrase: "Google",
            createdAt: "2022-05-04T19:10:14.000Z",
            dateOfBirth: "22/12/2400",
            email: "musediqolamilekan567@gmail.com",
            firstName: "Musediq Olamilekan",
            gender: "Male",
            genoType: "AA",
            hobby: "Coding",
            id: 2,
            inSearch: "Search",
            interest: "Interest",
            isMatched: true,
            latitude: "3456789",
            longitude: "3456789",
            loveLang: "Love",
            nationality: "Nigerian",
            religion: "Islam",
            tribe: "Yoruba",
            updatedAt: "2022-05-21T11:11:30.000Z",
            user_id: 6,
        },
        {
            avatar: "nullhttps://api.philiamatch.com/storage/public/avatars/avatar--1653131490579.jpg,",
            catchyPhrase: "Google",
            createdAt: "2022-05-04T19:54:19.000Z",
            dateOfBirth: "22/12/2400",
            email: "musediqoln567@gmail.com",
            firstName: "Musediq Olamilekan",
            gender: "Male",
            genoType: "AA",
            hobby: "Coding",
            id: 3,
            inSearch: "Search",
            interest: "Interest",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "Love",
            nationality: "Nigerian",
            religion: "Islam",
            tribe: "Yoruba",
            updatedAt: "2022-05-21T11:11:30.000Z",
            user_id: 2,
        },
        {
            avatar: null,
            catchyPhrase: "Nothing flashy",
            createdAt: "2022-05-04T22:26:47.000Z",
            dateOfBirth: "Wed Nov 21 1990 00:00:00 GMT+0100 (WAT)",
            email: "gbolahanbamigbola2000@gmail.com ",
            firstName: "Gbolahan",
            gender: "Female",
            genoType: "AS",
            hobby: "Playing Games",
            id: 4,
            inSearch: "Love",
            interest: "NA",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "Gift",
            nationality: "United States",
            religion: "Others",
            tribe: "Yoruba",
            updatedAt: "2022-05-04T22:26:47.000Z",
            user_id: 4,
        },
        {
            avatar: "nullavatar--1652174863926.png,",
            catchyPhrase: "",
            createdAt: "2022-05-04T22:36:07.000Z",
            dateOfBirth: "",
            email: "",
            firstName: "",
            gender: "Male",
            genoType: "",
            hobby: "",
            id: 5,
            inSearch: "",
            interest: "NA",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "",
            nationality: "",
            religion: "Muslim",
            tribe: "",
            updatedAt: "2022-05-10T09:27:43.000Z",
            user_id: 5,
        },
        {
            avatar: "nullavatar--1652973540440.jpg,avatar--1652975644996.jpg,",
            catchyPhrase: "Love's Goood..",
            createdAt: "2022-05-05T11:10:15.000Z",
            dateOfBirth: "Mon Dec 13 1993 00:00:00 GMT+0100 (WAT)",
            email: "ayobamz@gmail.com",
            firstName: "Ayomikun",
            gender: "Others",
            genoType: "AC",
            hobby: "Playing Games,Gyming",
            id: 6,
            inSearch: "love",
            interest: "NA",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "Gift,Quality Time",
            nationality: "United States",
            religion: "Others",
            tribe: "Yoruba",
            updatedAt: "2022-05-19T15:54:05.000Z",
            user_id: 8,
        },
        {
            avatar: null,
            catchyPhrase: "no phrase",
            createdAt: "2022-05-05T16:57:12.000Z",
            dateOfBirth: "Wed Dec 06 2000 00:00:00 GMT+0100 (WAT)",
            email: "jayman@gmail.com",
            firstName: "Joel",
            gender: "Female",
            genoType: "",
            hobby: "Playing Games,Gyming",
            id: 7,
            inSearch: "friendship",
            interest: "NA",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "Act of Service,Physical Touch,Words of affirmation",
            nationality: "United States",
            religion: "Others",
            tribe: "Igbo",
            updatedAt: "2022-05-05T16:57:12.000Z",
            user_id: 9,
        },
        {
            avatar: null,
            catchyPhrase: "",
            createdAt: "2022-05-05T17:22:03.000Z",
            dateOfBirth: "Sun Jan 09 2005 00:00:00 GMT+0100 (WAT)",
            email: "apochike@gmail.com",
            firstName: "Chike",
            gender: "Male",
            genoType: "",
            hobby: "",
            id: 8,
            inSearch: "",
            interest: "NA",
            isMatched: false,
            latitude: null,
            longitude: null,
            loveLang: "",
            nationality: "Afghanistan",
            religion: "Muslim",
            tribe: "Igbo",
            updatedAt: "2022-05-05T17:22:03.000Z",
            user_id: 10,
        },
    ]


firstName, Gender, DOB = new Array(data.length);

for (let item of data){
		firstName[item.id-1] = item.firstName;
		Gender[item.id-1] = item.gender;
		DOB[item.id-1] = item.dateOfBirth;
};

filteredList = {};
	filteredList.firstname= firstName.slice(),
	filteredList.gender= Gender.slice(),
	filteredList.dateOfBirth= DOB.slice();


console.log(filteredList.firstname[0]);